#!/usr/bin/env python3
"""Regenerate the theme codebook table in appendix/codebook-and-traceability.tex.

Source of truth: context/interviews-round1/First Open Coding.docx.
That document holds the six per-interview code tables (435 rows of initial
code plus German excerpt) and, after them, the 64 themes with the German
excerpts grouped under each. The appendix reproduces the second part: every
theme, its label, the interviews it recurred in, its disposition, and each
excerpt in the author's English translation beside the German original.

The English translations live in tools/codebook_translations.json, keyed
"<theme>.<index>", index being the excerpt's position under that theme in the
source document. They are written once by hand and checked in, so a rebuild
is deterministic and a changed translation shows up in a diff.

Usage: python3 tools/build_codebook.py        (writes the .tex fragment)
       python3 tools/build_codebook.py --check (verifies it is up to date)
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

DOCX = 'context/interviews-round1/First Open Coding.docx'
TRANS = 'tools/codebook_translations.json'
THEMES = 'tools/codebook_themes.json'
OUT = 'appendix/theme-codebook-table.tex'

# The disposition recorded per theme in the source document, mapped onto the
# scope boundaries the thesis states by number. "No mobile app" is not one of
# them; it follows from the platform decision in Section 2.3 (see ANWEISUNGEN
# section 5).
STATUS = {
    'FEATURE': 'Carried forward',
    'no live connection to CMS or LMS': 'Excluded, OOS3',
    'no live connection to CMS or LMS or any other platform': 'Excluded, OOS3',
    'No automated Planner': 'Excluded, OOS1',
    'no community feature': 'Excluded, OOS4',
    'No within semester planner': 'Excluded, OOS2',
    'Desktop-scale web application': 'Excluded, desktop-scale web application '
                                    '(Section~\\ref{sec:overall-scope})',
    'Artefact of clarifying the scope':
        'Methodological artefact, clarifying the scope of the interview',
    'Artefact of asking participants for new round of interview':
        'Methodological artefact, asking participants about a follow-up round',
}


def source_themes():
    from docx import Document
    d = Document(DOCX)
    ps = [p.text for p in d.paragraphs]
    themes, cur = {}, None
    for t in ps:
        st = t.strip()
        m = re.match(r'^C(\d{1,2})\s*[\u2014\u2013-]\s*(.+)$', st)
        if m:
            cur = int(m.group(1))
            themes[cur] = []
        elif cur and st.startswith('(I'):
            mm = re.match(r'^\(I(\d)\)\s*(.*)$', st)
            themes[cur].append((int(mm.group(1)), mm.group(2).strip()))
    return themes


def appendix_meta():
    """Theme label, n and disposition, from tools/codebook_themes.json.

    That file was extracted once from the codebook table this script replaced,
    which in turn came from the source document. Editing a label or a
    disposition means editing it there.
    """
    raw = json.load(open(THEMES, encoding='utf-8'))
    meta = {}
    for tid, m in raw.items():
        disp = None
        for key, val in STATUS.items():
            if key in m['status_source']:
                disp = val
                break
        if disp is None:
            raise SystemExit('unmapped disposition for T%s: %s' % (tid, m['status_source']))
        meta[int(tid)] = {'n': m['n'], 'label': m['label'], 'disp': disp}
    return meta


def tex_escape(s):
    s = s.replace('\\', '').replace('&', '\\&').replace('_', '\\_')
    s = s.replace('#', '\\#').replace('$', '\\$')
    s = re.sub(r'(?<!\\)%', '\\\\%', s)
    # straight quotes in the source become the house quotation form
    s = s.replace('\u201c', '\\enquote{').replace('\u201d', '}')
    s = s.replace('\u2018', '`').replace('\u2019', "'")
    return s


def build():
    themes = source_themes()
    meta = appendix_meta()
    en = json.load(open(TRANS, encoding='utf-8'))
    if set(themes) != set(meta):
        raise SystemExit('theme ids differ between the source document and the appendix')

    out = [
        '% Generated by tools/build_codebook.py -- do not edit by hand.',
        '\\small',
        '\\begin{longtable}{@{}p{0.7cm}p{6.0cm}p{6.0cm}@{}}',
        '\\toprule',
        '\\textbf{Int.} & \\textbf{Excerpt (translated)} & '
        '\\textbf{Excerpt (German original)} \\\\',
        '\\midrule',
        '\\endfirsthead',
        '\\toprule',
        '\\textbf{Int.} & \\textbf{Excerpt (translated)} & '
        '\\textbf{Excerpt (German original)} \\\\',
        '\\midrule',
        '\\endhead',
        '\\bottomrule',
        '\\endfoot',
    ]
    for tid in sorted(themes):
        m = meta[tid]
        head = ('\\textbf{T%d} --- %s \\quad ($n=%d$; %s)'
                % (tid, m['label'], m['n'], m['disp']))
        out.append('\\multicolumn{3}{@{}p{12.9cm}@{}}{%s} \\\\[2pt]' % head)
        for i, (iv, de) in enumerate(themes[tid]):
            # the source occasionally appends an analyst's note to an excerpt,
            # e.g. "(also appears under C19; kept here as ...)". That is not
            # speech and it still carries the pre-rename identifiers, so it is
            # dropped here; where it matters, the English column says so.
            de = re.sub(r'\s*\((?:also|kept)[^)]*\)\s*$', '', de).strip()
            key = '%d.%d' % (tid, i)
            if key not in en:
                raise SystemExit('missing translation for ' + key)
            out.append('I%d & \\enquote{%s} & %s \\\\'
                       % (iv, tex_escape(en[key]), tex_escape(de)))
        out.append('\\addlinespace')
    out.append('\\end{longtable}')
    out.append('\\normalsize')
    return '\n'.join(out) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    args = ap.parse_args()
    text = build()
    if args.check:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != text:
            print('FAIL  %s is out of date; run tools/build_codebook.py' % OUT)
            sys.exit(1)
        print('%s is up to date' % OUT)
        return
    open(OUT, 'w', encoding='utf-8').write(text)
    print('wrote %s (%d lines)' % (OUT, text.count('\n')))


if __name__ == '__main__':
    main()
